server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/moroccan_cars
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Passeword1
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
jwt:
  secret: 7491aaebc384e55531426637360acc475594a998
  hdr: ACCESS_TOKEN